sonar.organization=rhy0u
sonar.projectKey=rhy0u_bass-training

sonar.sources=apps/web/src,packages/ui/src,packages/database/src
sonar.tests=packages/ui/src,apps/web/src,packages/database/src
sonar.test.inclusions=**/*.stories.tsx,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/*.stories.tsx,**/dist/**,**/.next/**,**/coverage/**

sonar.typescript.lcov.reportPaths=packages/ui/coverage/lcov.info,apps/web/coverage/lcov.info,packages/database/coverage/lcov.info

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
